name: "CI App"

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "test/**"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
      - "docker-compose.yml"
      - "tsconfig.json"
      - "tsconfig.build.json"
      - "nest-cli.json"
      - ".github/workflows/ci-app.yml"

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

env:
  NODE_VERSION: "22"

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-region: sa-east-1
          role-to-assume: arn:aws:iam::958157975241:role/ecr-role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build docker image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ steps.generate_tag.outputs.sha }}
        run: |
          docker build -t $ECR_REGISTRY/estudos-ci-cd:$TAG .
          docker tag $ECR_REGISTRY/estudos-ci-cd:$TAG $ECR_REGISTRY/estudos-ci-cd:latest
          docker push --all-tags $ECR_REGISTRY/estudos-ci-cd
          IMAGE=$(echo $ECR_REGISTRY/estudos-ci-cd:$TAG)
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-region: sa-east-1
          role-to-assume: arn:aws:iam::958157975241:role/tf-role

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8

      - name: Terraform Init
        working-directory: iac/service
        run: terraform init

      - name: Deploy to ECS Express
        working-directory: iac/service
        env:
          TAG: ${{ steps.generate_tag.outputs.sha }}
        run: terraform apply -auto-approve -var="image_tag=$TAG"
