name: "CI"

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "test/**"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
      - "docker-compose.yml"
      - "tsconfig.json"
      - "tsconfig.build.json"
      - "nest-cli.json"
      - ".github/workflows/ci.yml"

permissions:
  contents: read
  id-token: write

env:
  NODE_VERSION: "22"

jobs:
  build:
    name: "Build and Push"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-region: sa-east-1
          role-to-assume: arn:aws:iam::958157975241:role/ecr-role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ steps.generate_tag.outputs.sha }}
        run: |
          docker build -t $REGISTRY/estudos-ci-cd:$TAG .
          docker push $REGISTRY/estudos-ci-cd:$TAG

      # - name: Push image
      #   run: docker push lanprd/estudos-ci-cd:${{ steps.generate_tag.outputs.sha }}
